### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by buxuele** [anbergem/cvhelper#3]
pip3, ubuntu 18.10 :
Could not find a version that satisfies the requirement opencv-wrapper (from versions: )
No matching distribution found for opencv-wrapper

please help.

**Comment by anbergem** [comment]
I'm assuming this is because you are using Python < 3.7. When writing the library I wanted to utilize the new `dataclasses` module in Python 3.7. Therefore this was added as a requirement. I'm pretty sure there is a backporting library, that makes it usable for previous versions as well. I'll look into adding that.

**Comment by anbergem** [comment]
Updated to version 0.2.0 now, @buxuele. This supports both Python 3.6 and OpenCV 4. It's uploaded to PyPi, so try again with the pip install!
